replicaCount: 2

image:
  repository: cloudcart-placeholder
  tag: k8s-v1
  pullPolicy: IfNotPresent

namespace:
  create: false

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi